### ISSUE TITLE
Add button to export M3U from playlist editor

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/pload#18]
It would be nice to export a M3U of the current playlist from the playlist editor interface. We should be able to do this entirely on the client side.

**Comment by mutantmonkey** [comment]
I'm actually wondering if we might be better off doing this on the server side. It's certainly easier to implement, and we could do it for playlists have already played as well.

**Comment by echarlie** [comment]
what's the utility of this, besides being able to re-schedule a show?

**Comment by mutantmonkey** [comment]
DJs might just want to save their playlists for posterity.

**Comment by echarlie** [comment]
Could we instead leverage trackman's "send me my playlist" functionality for this?

**Comment by mutantmonkey** [comment]
Not really. That feature doesn't work for automation and Trackman doesn't know that actual URL of files that are played. The closest you'd be able to get to that would be to create cue files from the playlist itself. Trackman used to support this, but due to complications with file naming, this was removed in http://github.com/wuvt/trackman/commit/bbf97b91593e3ea882567fe750583ff75458031b. I meant to write a separate tool for this  (possibly one we could ship with Trackman) that uses the Trackman API to get a list of tracks, but I never got around to it.
