### ISSUE TITLE
Consider Reliscensing?

### ISSUE THREAD

**Issue by echarlie** [wuvt/pload#8]
Currently Pload is liscensed under a 3-clause BSD liscence. Ignoring my personal distaste for it (I think ISC is better suited for those intentions), pload has grown beyond its' original scope. Should we reliscense under AGPL-3 or MPL-2, to be more consistent with other projects?

**Comment by mutantmonkey** [comment]
I mean I would say AGPLv3 to be consistent with Trackman. I am actually curious how we ended up with this license; I usually either do GPL or ISC so I will go have to back and review things to see if there's a reason.
